version: 2
updates:
  # Mise à jour des dépendances Python
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "python"

  # Mise à jour des dépendances npm
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "javascript"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      angular:
        patterns:
          - "angular*"
          - "@angular*"
      typescript:
        patterns:
          - "@typescript*"
