version: 2
updates:
  # Mise à jour des dépendances Python
  - package-ecosystem: "pip"
    directory: "/back"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "dependencies"
      - "python"
      - "backend"
      - "dependabot"

  # Mise à jour des dépendances npm
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
      - "dependabot"
    ignore: 
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      angular:
        patterns:
          - "angular*"
          - "@angular*"
      typescript:
        patterns:
          - "@typescript*"
