name: megacte

configs:
  api-config:
    file: ./config_local_nuxt_kc_xp/api-config.yml
  private-key:
    file: ./config_local_nuxt_kc_xp/private_key.pem
  public-certificate:
    file: ./config_local_nuxt_kc_xp/publicCertificate_tech.pem

services:
  backend:
    image: megacte-backend
    build:
      context: ./back
      dockerfile: Dockerfile
    configs:
      - source: api-config
        target: /megacte-back/config/config.yml
      - source: private-key
        target: /megacte-back/config/private_key.pem
      - source: public-certificate
        target: /megacte-back/config/publicCertificate_tech.pem
    depends_on:
      - db
    environment:
      MEGACTE_LOGLEVEL: "DEBUG"
    ports:
      - "8080:8080"
    networks:
      - megacte-front-tier
      - megacte-back-tier

  frontend:
    image: megacte-frontend-nuxt
    build:
      context: ./nuxt-web-app
      dockerfile: Dockerfile
    environment:
      APP_URL: ${APP_URL}
      API_URL: ${API_URL}
      AUTH_ORIGIN: ${AUTH_ORIGIN}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - megacte-front-tier

  db:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - megacte-db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      megacte-back-tier:
        aliases:
          - megacte-db

volumes:
  megacte-db-data:

networks:
  megacte-back-tier:
  megacte-front-tier:
