name: megacte

configs:
  api-config:
    file: ./config_local_angular_kc_preprod/api-config.yml
  settings:
    file: ./config_local_angular_kc_preprod/settings.json
  private-key:
    file: ./config_local_angular_kc_preprod/private_key.pem
  public-certificate:
    file: ./config_local_angular_kc_preprod/publicCertificate_tech.pem

services:
  backend:
    image: megacte-backend
    build:
      context: ./back
    command: ["./docker-backend-start.sh", "--dev"]
    configs:
      - source: api-config
        target: /megacte-back/config/config.yml
      - source: private-key
        target: /megacte-back/config/private_key.pem
      - source: public-certificate
        target: /megacte-back/config/publicCertificate_tech.pem
    depends_on:
      - db
    environment:
      MEGACTE_LOGLEVEL: "DEBUG"
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "8080:8080"
    networks:
      - megacte-front-tier
      - megacte-back-tier

    volumes:
      - type: bind
        source: ./back/app
        target: /megacte-back/app

  frontend:
    image: megacte-frontend
    build:
      context: ./web-app
      dockerfile: Dockerfile.dev
    command: npm start -- --host 0.0.0.0 --port 80 --public-host http://localhost
    configs:
      - source: settings
        target: /app/src/assets/settings.json
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - megacte-front-tier
    volumes:
      - type: bind
        source: ./web-app/src
        target: /app/src

  db:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - megacte-db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      megacte-back-tier:
        aliases:
          - megacte-db

volumes:
  megacte-db-data:

networks:
  megacte-back-tier:
  megacte-front-tier:
