pastell:
  url : <url>
  user : <user>
  password : <mdp>

keycloak:
  token_url: <token>
  refresh_url: <refresh>
  auth_url: <auth>
  jwks_url: <jwks>
  client_id: megacte

database:
  pwd : <pwd>
  user : megacte
  host : localhost
  port : 54032
  database: megacte

s2low:
  url: <urm>
  path_certificate: <certificat .pem>
  path_key: <private_key.pem>
  key_password: <password>