pastell:
  url : <url>
  user : <user>
  password : <mdp>

keycloak:
  token_url: <token>
  refresh_url: <refresh>
  auth_url: <auth>
  jwks_url: <jwks>
  client_id: megacte

Database:
  pwd : <pwd>
  user : <user>
  host : <host>
  port : <port>
  database: <db name>