FROM node:20-trixie-slim

WORKDIR /app

COPY package.json .
COPY angular.json .
COPY postcss.config.js .
COPY tailwind.config.js .
COPY tsconfig.app.json .
COPY tsconfig.json .
COPY tsconfig.spec.json .

RUN npm install

