server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    error_log /dev/stdout info;

    location ~* \.(js|css|png|jpe?g|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public";
    }

    location = /assets/settings.json {
        expires 0;
        add_header Cache-Control "no-cache";
        try_files /assets/settings.json =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
