"""flux available

Revision ID: e226d0c2c6a5
Revises: 1cf3d83d62af
Create Date: 2024-09-26 08:56:14.598359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e226d0c2c6a5"
down_revision: Union[str, None] = "1cf3d83d62af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flux_available",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flux_id_pastell", sa.String(), nullable=True),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flux_id_pastell"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flux_available")
    # ### end Alembic commands ###
