"""connecteur tdt

Revision ID: 7e24685e8a73
Revises: e226d0c2c6a5
Create Date: 2024-10-16 12:45:27.812523

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e24685e8a73"
down_revision: Union[str, None] = "e226d0c2c6a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connecteur_auth_tdt",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_e", sa.Integer(), nullable=False),
        sa.Column("flux", sa.String(), nullable=False),
        sa.Column("login_tech_tdt", sa.String(), nullable=False),
        sa.Column("pwd_tech_tdt", sa.String(), nullable=False),
        sa.Column("pwd_key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_e", "flux"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connecteur_auth_tdt")
    # ### end Alembic commands ###
