name: Build app

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [main]
    tags: [v*.*.*]
    paths:
      - ".github/workflows/**"
      - "back/**"
      - "web-app/**"
      - "docker/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "back/**"
      - "web-app/**"
      - "docker/**"

jobs:
  
  build-backend:
    name: Python build test analyse
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.2'

    - name: Install dependencies
      run: |
        cd back/
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        cd back/
        pip install -r requirements_dev.txt
        pytest -Werror --cov=app --cov-report=xml --cov-branch
    
    - name: fix coverage paths for sonar
      run: |
        sed -i 's|<source>/home/runner/work/MegActe/MegActe/back/app</source>|<source>/github/workspace/back/app</source>|' back/coverage.xml
  
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



  build-angular :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: web-app/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('web-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        working-directory: web-app
        run: |
          npm install

      - name: Linting
        working-directory: web-app
        run: |
          npm run lint

      - name: Build angular
        working-directory: web-app
        run: |
          npm run build --prod

      - uses: actions/upload-artifact@v4
        name: cache-artifact
        with:
          name: web-app-dist
          path: web-app/dist
