name: Build app

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["main","develop"]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
      # The branches below must be a subset of the branches above
      branches: [ "main", "develop" ]

permissions:
  contents: read
  id-token: write
  packages: write


jobs:
  Analyse-code:
    name: Analyse Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.3.0
        with:
          project-token: ${{ secrets.CODACY_API }}
          upload: true
          max-allowed-issues: 1000

  build-angular :
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: web-app/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        working-directory: web-app
        run: |
          npm install

      - name: Build angular
        working-directory: web-app
        run: |
          npm run build --prod

      - uses: actions/upload-artifact@v4
        name: cache-artifact
        with:
          name: web-app-dist
          path: web-app/dist


  build-docker-web-app :
    uses: ./.github/workflows/build-push-docker.yml
    needs: build-angular
    with:
      context: .
      dockerfile: ./docker/web/Dockerfile
      image-name: ${{ github.repository_owner }}/megacte-web
      artifact: web-app-dist
      path-artifact: web-app/dist

  build-back:
    uses: ./.github/workflows/build-push-docker.yml
    with:
      context: back
      dockerfile: ./docker/back/Dockerfile
      image-name: ${{ github.repository_owner }}/megacte-back