name: Deploy-Megacte

on:
  workflow_run:
    workflows: [Build app]
    types: [completed]

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: get version
        id: get-version
        run: echo "::set-output name=version::sha-${GITHUB_SHA::7}"

  deploy:
    runs-on: ubuntu-latest
    needs: [get-version]
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SERVEUR }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          script: |
            export version=${{ needs.get-version.outputs.version }} && export $(cat .env) && docker stack deploy -c stack/compose/megacte/megacte.yml megacte
            