name: Deploy-Megacte

on:
  workflow_run:
    workflows: [Build app]
    branches: [main]
    types: [completed] # se lance uniquement sur la default branch

jobs:
  deploy-on-xp:
    name: Deploiement XP
    runs-on: ubuntu-latest
    steps:
      - name: get version
        id: get-version
        run: echo "VERSION=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Deploy version
        uses: appleboy/ssh-action@v1.0.3
        env:
          VERSION: ${{env.VERSION}}
         
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SERVEUR }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          envs: VERSION
          script: |
            echo "Deploiement version $VERSION" 
            export version=$VERSION && export $(cat .env) && docker stack deploy -c stack/compose/megacte/megacte.yml megacte
